config/routes.rb
StripePayment::Application.routes.draw do
  resources :payments

   root :to => 'payments#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    @payments = Payment.all
  end

  def show
  end

  def create
    # set your secret key: remember to change this to your live secret key in production
    # see your keys here https://manage.stripe.com/account
    Stripe.api_key = "sk_test_PCIdeoqevlIdaN8hvBwJP6uH"

    # get the credit card details submitted by the form
    logger.info(" create!!!!!!!!!!!!!!!!!!! ")
    logger.info(params)
    token = params[:stripeToken]

    if params[:subscribe]
      # create a Customer
      customer = Stripe::Customer.create(
        :card => token,
        :plan => "basic",
        :email => "payinguser@example.com"
      )
    else
      # create the charge on Stripe's servers - this will charge the user's card
      charge = Stripe::Charge.create(
        :amount => 1200000, # amount in cents, again
        :currency => "usd",
        :card => token,
        :description => "payinguser@example.com"
      )
    end

    logger.info charge
    @charge = charge
    flash[:notice] = "You've sent money!"
    redirect_to payment_path(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StripePayment" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "https://js.stripe.com/v1/" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" %>
    <%= javascript_include_tag "stripe" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">StripePayment</a>
          <div class="container nav-collapse">
            <ul class="nav">
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= yield %>
        <footer>
          <p>&copy; Ami & Julie 2012</p>
        </footer>
      </div>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/payments/_form.html.erb
<div class="payment-errors"></div>

<form action="<%= payments_path %>" method="POST" id="payment-form">
  <div class="form-row">
    <label>Card Number</label>
    <input type="text" size="20" autocomplete="off" class="cc_number required"/>
  </div>
  <div class="form-row">
    <label>CVC</label>
    <input type="text" size="4" autocomplete="off" class="cc_cvc required input-mini"/>
  </div>
  <div class="form-row">
    <label>Expiration (MM/YYYY)</label>
    <input type="text" size="2" class="cc_exp_month required input-mini"/>
    <span> / </span>
    <input type="text" size="4" class="cc_exp_year required input-mini"/>
  </div>
  <div class="form-row">
    <label>First Name</label>
    <div class="controls controls-row">
      <input type="text" size="25" autocomplete="off" class="firstname" name="firstname"/>
    </div>
  </div>
  <div class="form-row">
    <label>Last Name</label>
    <input type="text" size="25" autocomplete="off" class="lastname" name="lastname"/>
  </div>
  <div class="form-row">
    <label>Address: Street</label>
    <input type="text" size="20" autocomplete="off" class="address-street"/>
  </div>
  <div class="form-row">
    <label>City</label>
    <input type="text" size="25" autocomplete="off" class="address-city" name="city"/>
  </div>
  <div class="form-row">
    <label>State</label>
    <input type="text" size="25" autocomplete="off" class="address-state" name="state"/>
  </div>
  <div class="form-row">
    <label>Zip</label>
    <input type="text" size="5" autocomplete="off" class="address-zip input-mini" name="zip"/>
  </div>
  <div class="form-row">
    <label>Phone Number</label>
    <input type="text" size="20" autocomplete="off" class="phone-number" name="phone"/>
  </div>
  <div class="form-row">
    <label>Email</label>
    <input type="text" size="20" autocomplete="off" class="email" name="email"/>
  </div>
  <div class="form-row">
    <label class="checkbox inline">
      <input type="checkbox" class="subscribe" name="subscribe" value="subscribe">Subscribe?
    </label>
  </div>
  <br />
  <button type="submit" class="submit-button btn btn-primary">Submit Payment</button>
</form>

app/views/payments/index.html.erb
<% if flash[:notice] %>
  <div class="success"><%= flash[:notice] %></div>
<% end %>

<% @payments.each do |payment| %>

<% end %>

<%= render :partial => 'form' %>

app/views/payments/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><p><%= flash[:notice] %></p></div>
<% end %>

<% if @charge %>
  <p>Thank you for your payment! $<%= @charge.amount / 100 %> has been charged to <%= @charge.email %>.</p>
<% end %>

<p><%= link_to "Make another payment", payments_path %></p>